version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
