version: '2'
services:
  azure-mock:
    image: ghcr.io/navikt/azure-mock:latest
    container_name: azure-mock
    restart: on-failure
    ports:
      - "8100:8100"
    mem_limit: 64m
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: on-failure
    mem_limit: 64m
    environment:
      REDIS_PASSWORD: foobar
  oidc-auth-proxy:
    build: ../.
    container_name: oidc-auth-proxy
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - "./.env"
    depends_on:
      - azure-mock
      - redis
    mem_limit: 64m