version: '2'
services:
  azure-mock:
    image: docker.pkg.github.com/navikt/azure-mock/azure-mock:latest
    container_name: azure-mock
    restart: on-failure
    ports:
      - "8100:8100"
    mem_limit: 64m
  oidc-auth-proxy:
    build: ../.
    container_name: oidc-auth-proxy
    restart: on-failure
    ports:
      - "8101:8101"
    env_file:
      - "./oidc-auth-proxy.env"
    depends_on:
      - azure-mock
    mem_limit: 64m