name: Build and deploy Docker
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - master
jobs:
  docker:
    name: Laste opp docker image
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1
      - name: Sette opp Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Installere dependencies
        run: npm install
      - name: Bygge Dist
        run: npm run build
      - name: Sette Docker- navn og tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/k9-punsj-oidc-auth-proxy
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Bygge Docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: Laste opp Docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}