name: Build and deploy Docker Image

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'test/**'
    branches:
      - master
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_IMAGE: ghcr.io/${{ github.repository }}
  MAJOR_VERSION: "3"

jobs:
  docker:
    name: Build and deploy Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write # trivy
      packages: write
      security-events: write #codeql
      actions: read #codeql
    steps:
      - name: Hente kode
        uses: actions/checkout@v4

      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygge app & kjøre integration tests
        shell: bash
        run: |
          cd startup-utils
          ./start-for-integration-tests.sh --detach
          cd ../integration-tests
          npm install
          npm run test
          cd ../startup-utils
          docker-compose down
          cd ..

      - name: Sette Docker variabler
        run: |
          echo "TAG=${MAJOR_VERSION}.$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "RC_TAG=${MAJOR_VERSION}.$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)-RC" >> $GITHUB_ENV

      - name: Bygg & last opp Docker image (Release)
        if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
        run: |
          docker build --pull --tag ${BASE_IMAGE}:${TAG} --tag ${BASE_IMAGE}:latest .
          docker push ${BASE_IMAGE} --all-tags
          
      - name: Set image for trivy
        run: echo "IMAGE=${BASE_IMAGE}:${TAG}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ env.IMAGE }}
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Bygg & last opp Docker image (Release Candidate)
        if: github.ref != 'refs/heads/master'
        run: |
          docker build --pull --tag ${BASE_IMAGE}:${RC_TAG} .
          docker push ${BASE_IMAGE}:${RC_TAG}
