name: Build and deploy Docker Image

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'test/**'
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  docker:
    name: Build and deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1

      - name: Sette opp Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Bygge app & kjøre integration tests
        shell: bash
        run: |
          echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
          cd startup-utils
          ./start-for-integration-tests.sh --detach
          cd ../integration-tests
          npm install
          npm run test
          cd ../startup-utils
          docker-compose down
          cd ..

      - name: Sette Docker variabler
        run: |
          echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Bygg & last opp Docker image
        run: |
          docker build --pull --tag ${BASE_IMAGE}:${TAG} --tag ${BASE_IMAGE}:latest .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${BASE_IMAGE}:${TAG}
          docker push ${BASE_IMAGE}:latest
