name: Build and run integration tests

on: [pull_request]

jobs:
    docker:
        name: Build and run integration tests
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v1
            - name: Sette opp Node
              uses: actions/setup-node@v1
              with:
                  node-version: '15.x'
            - name: Bygge app & kjøre integration tests
              shell: bash
              run: |
                  docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  cd startup-utils
                  ./start-for-integration-tests.sh --detach
                  cd ../integration-tests
                  npm install
                  npm run test
                  cd ../startup-utils
                  docker-compose down
                  cd ..
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}